/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (duke-nukem-land-of-the-babes-)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x80059A64u
#define func_80059A64 BootEntry  /* alias */
